// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7a-RvYyekTGp923QqwCE95nriPpjQxok',
    appId: '1:608227876008:web:591d5f6cd9d30fcc88369d',
    messagingSenderId: '608227876008',
    projectId: 'tickletockletackle',
    authDomain: 'tickletockletackle.firebaseapp.com',
    storageBucket: 'tickletockletackle.appspot.com',
    measurementId: 'G-V480N1VE0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcGTTVzE_6bXepr1EC4buwvqLevxMexcQ',
    appId: '1:608227876008:android:17b1cb199843147a88369d',
    messagingSenderId: '608227876008',
    projectId: 'tickletockletackle',
    storageBucket: 'tickletockletackle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRb80dBReZXtJNGE6n8pnwfhvaC8u6EmE',
    appId: '1:608227876008:ios:e58d6fb7f109ed2e88369d',
    messagingSenderId: '608227876008',
    projectId: 'tickletockletackle',
    storageBucket: 'tickletockletackle.appspot.com',
    iosClientId: '608227876008-3lhhuli5ebcldoqp6aip5hbkug1doq7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.tickleTackleTockle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRb80dBReZXtJNGE6n8pnwfhvaC8u6EmE',
    appId: '1:608227876008:ios:626cbad258eaef7d88369d',
    messagingSenderId: '608227876008',
    projectId: 'tickletockletackle',
    storageBucket: 'tickletockletackle.appspot.com',
    iosClientId: '608227876008-g8imcec1g8b0k7028c6vkvhc619if0fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tickleTackleTockle.RunnerTests',
  );
}
