// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmStIBfAp8DutpA7k1DuCPzGJvvNXaVU',
    appId: '1:723020757063:web:e27de60edb3bd1538a9962',
    messagingSenderId: '723020757063',
    projectId: 'tickletackletockle-a804',
    authDomain: 'tickletackletockle-a804.firebaseapp.com',
    storageBucket: 'tickletackletockle-a804.appspot.com',
    measurementId: 'G-GWZ65Z9C67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjilUvGrLzTApip0BG1zaGdN82sedKu2Y',
    appId: '1:723020757063:android:4b8c9449708ca87c8a9962',
    messagingSenderId: '723020757063',
    projectId: 'tickletackletockle-a804',
    storageBucket: 'tickletackletockle-a804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIyId71Y5MJgaMXtCi-0L-IYjcYkfJ17A',
    appId: '1:723020757063:ios:51fb0fb050b6e8ba8a9962',
    messagingSenderId: '723020757063',
    projectId: 'tickletackletockle-a804',
    storageBucket: 'tickletackletockle-a804.appspot.com',
    iosClientId: '723020757063-ock2vhkpan6vfed5s4tr255p0s1sbh2f.apps.googleusercontent.com',
    iosBundleId: 'com.a804.tickleTackleTockle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIyId71Y5MJgaMXtCi-0L-IYjcYkfJ17A',
    appId: '1:723020757063:ios:9fcf554dc1c4dd7b8a9962',
    messagingSenderId: '723020757063',
    projectId: 'tickletackletockle-a804',
    storageBucket: 'tickletackletockle-a804.appspot.com',
    iosClientId: '723020757063-bkvthbqff8m5mhob537u9svhndj64mhr.apps.googleusercontent.com',
    iosBundleId: 'com.a804.tickleTackleTockle.RunnerTests',
  );
}
